#!/bin/bash

export MMG_SRC=$(pwd)
export MMG_INST="${MMG_SRC}/install"

rm -rf "${MMG_SRC}/build/Release"
rm -rf "${MMG_INST}"

cmake -H. -B build/Release -G Ninja \
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
-DCMAKE_BUILD_TYPE=Release \
-DBUILD=MMG2D \
-DBUILD_SHARED_LIBS=ON \
-DLIBMMG2D_STATIC=OFF \
-DLIBMMG2D_SHARED=ON \
-DUSE_SCOTCH=OFF \
-DUSE_ELAS=OFF \
-DUSE_VTK=OFF \
-DCMAKE_INSTALL_PREFIX:PATH=$MMG_INST
