#!/bin/bash

rm -rf build/Release
cmake -H. -B build/Release -G Ninja \
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
-DCMAKE_BUILD_TYPE=Release \
-DBUILD=MMG2D \
-DBUILD_SHARED_LIBS=ON \
-DLIBMMG2D_STATIC=OFF \
-DLIBMMG2D_SHARED=ON \
-DUSE_SCOTCH=OFF \
-DUSE_ELAS=OFF \
-DUSE_VTK=OFF \
-DCMAKE_INSTALL_PREFIX:PATH=install
