
rmdir /S /Q .\build

cmake -B build -G "Ninja" ^
-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE ^
-DCMAKE_BUILD_TYPE=Release ^
 ^
-DBUILD=MMG2D ^
-DLIBMMG2D_STATIC=OFF ^
-DLIBMMG2D_SHARED=ON ^
-DUSE_SCOTCH=OFF ^
-DUSE_ELAS=OFF ^
-DUSE_VTK=OFF ^
-DBUILD_TESTING=OFF ^
-DTEST_LIBMMG2D=OFF

cmake --build build
